Vagrant.configure("2") do |config|
  # Use the CentOS 7 base box
  config.vm.box = "centos/7"

  # Configure the virtual machine's resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Customize the VM name
  config.vm.define "centos_vm" do |centos_vm|
    centos_vm.vm.hostname = "centos-vm"
    
    # Set a static IP address
    centos_vm.vm.network "private_network", ip: "192.168.33.10"

    # Provision the VM to install Jenkins
   # centos_vm.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary packages
      #yum update -y
      #sudo yum install -y java-11-openjdk


      # Add Jenkins repository and import the key
     # wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
     # rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

      # Install Jenkins
     # yum install -y jenkins

      # Enable and start Jenkins service
     # systemctl enable jenkins
      #systemctl start jenkins

      # Open firewall ports for Jenkins
      #firewall-cmd --permanent --zone=public --add-port=8080/tcp
      #firewall-cmd --reload
    #SHELL
  end
end
